name: WWE Scraper Automatizado

on:
  schedule:
    # Se ejecuta de forma remota cada 6 horas automáticamente
    - cron: '0 */6 * * *'
  workflow_dispatch: # Permite que tú le des al botón de "Ejecutar ya" desde la web de GitHub

jobs:
  run-scraper:
    runs-on: ubuntu-latest # Levanta una máquina virtual Linux remota

    steps:
    - name: Descargar el código del repositorio
      uses: actions/checkout@v4

    - name: Configurar Node.js en el servidor
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar el Scraper
      run: node scraper.js
